/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE IF NOT EXISTS `amedigital` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_bin */;
USE `amedigital`;

CREATE TABLE IF NOT EXISTS `planet` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `cdate` datetime DEFAULT NULL,
  `climate` varchar(64) COLLATE latin1_bin DEFAULT NULL,
  `name` varchar(64) COLLATE latin1_bin DEFAULT NULL,
  `terrain` varchar(64) COLLATE latin1_bin DEFAULT NULL,
  `total_films` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1 COLLATE=latin1_bin;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
